version: "2"
services:
  nginx: #nginx服务
      build:
          context: ./nginx #dockerfile
      ports: #抛出的端口(主机)
          - "8082:80"
      volumes:
          - ./web:/home/www #项目目录
          - ./nginx/config:/etc/nginx/conf.d #配置文件映射
      container_name: nginx-service #容器名称
  fpm: #php的fpm服务
      build:
          context: ./php #dockerfile
      volumes:
          - ./web:/home/www #项目目录
          - ./php/config/www:/usr/local/php/etc/php-fpm.d #配置文件映射
          - ./php/config/phpfpm:/usr/local/php/etc #配置文件映射
      ports: #抛出的端口(主机)
          - "9000:9000"
      environment:
          - "DB_HOST=localhost"
          - "DB_DATABASE=cig" #默认数据库
      container_name: fpm-service #容器名称
  mastermariadb: #mariadb数据库主服务
      image: mariadb #镜像
      ports: #抛出的端口(主机)
          - "33061:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=root #root用户密码
          - MYSQL_DATABASE=cig #默认创建数据库
          - MYSQL_USER=slaveUser #创建用于主从复制的用户
          - MYSQL_PASSWORD=123456 #创建用于主从复制的用户的密码
      container_name: master-mariadb-service #容器名称
      networks:
          app_net:
            ipv4_address: 10.5.0.5
      volumes:
    #       - ./mariadb/master/data:/var/lib/mysql #数据永久挂载到宿主机
          - ./mariadb/master:/etc/mysql #配置文件映射

  slavemariadb: #mariadb数据库从服务
      image: mariadb #镜像
      ports:
          - "33062:3306" #抛出的端口(主机)
      environment:
          - MYSQL_ROOT_PASSWORD=root #root用户密码
          - MYSQL_DATABASE=cig #默认创建数据库
      volumes:
    #       - ./mariadb/slave/data:/var/lib/mysql #数据永久挂载到宿主机
          - ./mariadb/slave:/etc/mysql #配置文件映射
      container_name: slave-mariadb-service #容器名称
      networks:
          app_net:
            ipv4_address: 10.5.0.6
  redis: #redis缓存数据库服务
      image: redis #镜像
      ports:
          - "6379:6379" #抛出的端口(主机)
      environment:
          - REDIS=1
          - USER=redis #用户
          - REDIS_PASSWORD=123456 #密码
      volumes:
          - ./redis/config:/usr/local/redis #配置文件映射
      container_name: redis-service #容器名称
  mongo: #mongodb缓存数据库服务
      build:
          context: ./mongodb #dockerfile
    #   volumes:
    #       - ./mongodb/data:/data/db #数据永久挂载到宿主机
      ports: #抛出的端口(主机)
          - "47017:27017"
      container_name: mongodb-service #容器名称
networks:
  app_net:
     driver: bridge
     ipam:
        config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
